NewsDotNet.WebUI/Areas/Admin/Controllers/AdminHomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NewsDotNet.DomainModel.Entities;
using NewsDotNet.DomainModel.Abstract;

namespace NewsDotNet.WebUI.Areas.Admin.Controllers
{
    public class AdminHomeController : Controller
    {
        private IArticlesRepository _articleRepo;

        public AdminHomeController(IArticlesRepository articleRepo)
        {
            _articleRepo = articleRepo;
        }

        //
        // GET: /Admin/Home/
        public ActionResult Index()
        {
            return View(_articleRepo.All());
        }
	}
}

NewsDotNet.WebUI/Controllers/ArticlesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NewsDotNet.DomainModel.Entities;
using NewsDotNet.DomainModel.Abstract;

namespace NewsDotNet.WebUI.Controllers
{
    public class ArticlesController : Controller
    {
        private IArticlesRepository _articleRepo;

        public ArticlesController(IArticlesRepository articleRepo)
        {
            _articleRepo = articleRepo;
        }
        
        
        public ActionResult Show(string addressName)
        {
            var article = _articleRepo.GetByAddressName(addressName);
            if (null == article || article.State != ArticleStates.Published)
                return HttpNotFound();
            return View("Article", article);
        }

        public ActionResult Archive()
        {
            var articles = _articleRepo.All().Where(a => a.State == ArticleStates.Draft).OrderByDescending(a => a.CreatedTime).ToList();
            return View("List",articles);
        }
	}
}

NewsDotNet.WebUI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NewsDotNet.DomainModel.Abstract;
using NewsDotNet.DomainModel.Entities;

namespace NewsDotNet.WebUI.Controllers
{
    public class HomeController : Controller
    {
        private IMainPageEntitiesRepository _mainPageRepo;

        public HomeController(IMainPageEntitiesRepository mainPageRepo)
        {
            _mainPageRepo = mainPageRepo;
        }

        //
        // GET: /Home/
        public ActionResult Index()
        {
            var articles = _mainPageRepo.All().Where(a => a.Article.State == ArticleStates.Published).ToList();
            return View(articles);
        }
	}
}

NewsDotNet.WebUI/Controllers/TagsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NewsDotNet.DomainModel.Abstract;
using NewsDotNet.DomainModel.Entities;

namespace NewsDotNet.WebUI.Controllers
{
    public class TagsController : Controller
    {
        ITagsRepository _tagRepo;

        public TagsController(ITagsRepository tagRepo)
        {
            _tagRepo = tagRepo;
        }
        /// <summary>
        /// list of all tags in repository
        /// </summary>
        public PartialViewResult TagsCloud()
        {
            ///throw new NotImplementedException();
            return PartialView(_tagRepo.All().ToList());
        }
	}
}

NewsDotNet.WebUI/Areas/Admin/Views/AdminHome/Index.cshtml
@model IEnumerable<NewsDotNet.DomainModel.Entities.Article>

@{
    ViewBag.Title = "News.Net Admin: Список статей";
}

<div class="container">
    @if(@Model.Count() == 0){
        <div class="alert alert-info">Нет статей для отображения</div>
		}


    @foreach (var article in Model)
{
    <div class="panel panel-info" onclick="location.href='@Url.Action("Show", "Articles", new {area = "", addressName = article.AddressName })';">
        <div class="panel-heading">
            <h4 class="panel-title">
                @article.Title
            </h4>
        </div>
        <div class="panel-body">
            @Html.Raw(article.Body.Substring(0, Math.Min(article.Body.Length, 100)) + "...")
        </div>
        <div class="panel-footer">
            Автор: Аноним
        </div>
    </div>
}

</div>

NewsDotNet.WebUI/Areas/Admin/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="~/Content/Styles/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/Styles/AdminStyles.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <link rel="shortcut icon" type="image/x-icon" href="~/Content/Images/Layout/fav-icon.png" />
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-inverse" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href=@Url.Action("Index", "AdminHome")>
                        News.Net Admin
                    </a>
                </div>
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Статьи<b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="#">Список</a></li>
                                    <li><a href="#">Новая</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
                    <div class="container-fluid">
                        @RenderBody();
                    </div>
                </body>
            </html>

NewsDotNet.WebUI/Views/Articles/ArchiveArticlePartial.cshtml
@model NewsDotNet.DomainModel.Entities.Article

<li class="list-group-item" onclick="location.href='@Url.Action("Show", "Articles", new { addressName = Model.AddressName })';">
    
    <div class="panel panel-default">
        <div class="panel-body">
            <h3>@Model.Title</h3>
            @foreach (var tag in Model.Tags)
            {
                <span><a href="#"><label> </label>@tag.Name</a></span>
            }
            <p>@Html.Raw(Model.Body.Substring(0, Math.Min(Model.Body.Length, 250)) + "...")</p>
            <tr><td>Автор:@Model.AuthorId</td>       <td>Дата написания:@Model.CreatedTime</td>    <td>Дата последнего изменения:@Model.LastChangedTime</td></tr>
                 
               
        </div>
    </div>
</li>

﻿

NewsDotNet.WebUI/Views/Articles/Article.cshtml
@model NewsDotNet.DomainModel.Entities.Article

@{
    ViewBag.Title = Model.Title + " - News.Net";
}

<div class="wrap">
    <div class="single-page">
        <div class="single-page-artical">
            <div class="artical-content">
                <div class="published">@Model.LastChangedTime.ToString("f")</div>
                <h3>@Model.Title</h3>
                <img src="@("/" + Model.TitleImagePath)">
                <p>@Html.Raw(Model.Body)</p>
            </div>
            <div class="artical-links">
                <ul>
                    <li><a href="#"><img src="~/Content/Images/Layout/blog-icon2.png" title="Автор"><span>Автор</span></a></li>
                    <li><img src="~/Content/Images/Layout/blog-icon4.png" title="Теги">
                        @foreach (var tag in Model.Tags)
                        {
                            <span><a href="#">@tag.Name</a></span>
                        }
                    </li>
                </ul>
            </div>
            <div class="clear"> </div>
        </div>
        <br>
        @* INCLUDE DISQUS *@
        @Html.Partial("_Disqus")
    </div>
</div>

NewsDotNet.WebUI/Views/Articles/List.cshtml
@model IEnumerable<NewsDotNet.DomainModel.Entities.Article>

@{
    ViewBag.Title = "Archive";
}
<div class="wrap">
    <div id="main" role="main">
        <div class="container">
            <ul class="list-group">
                @foreach (var articleInfo in Model)
                {
                    @Html.Partial("ArchiveArticlePartial", articleInfo)
                   

                }
                </ul>
</div>
    
        </div>
    </div>

NewsDotNet.WebUI/Views/Home/FeaturedArticlePartial.cshtml
@model NewsDotNet.DomainModel.Entities.Article

<div class="item g1" onclick="location.href='@Url.Action("Show", "Articles", new { addressName = Model.AddressName })';">
    <img class="lazyOwl " data-src="@Model.TitleImagePath" alt="@Model.Title">
    <div class=" caption">
        <h3>@Model.Title</h3>
    </div>
</div>

NewsDotNet.WebUI/Views/Home/Index.cshtml
@model IEnumerable<NewsDotNet.DomainModel.Entities.MainPageEntity>

@{
    ViewBag.Title = "News.Net";
}

<div class="gallery container">
        @*<h1>Top Stories</h1>*@
        <!-- requried-jsfiles-for owl -->
        <link href="~/Content/Styles/owl.carousel.css" rel="stylesheet">
        <script src="~/Scripts/owl.carousel.js"></script>
        <script>
				    $(document).ready(function() {
					    $("#owl-demo").owlCarousel({
						    items : @Math.Min(@Model.Count(),3),
						    lazyLoad : true,
						    autoPlay : true,
						    pagination : false,
						    navigation : true,
						    navigationText :  true,
					    });
				    });
        </script>
        <!-- //requried-jsfiles-for owl -->
        <!-- start content_slider -->
        <div id="owl-demo" class="owl-carousel ">
            @foreach (var articleInfo in Model.Where(info => info.IsFeatured))
            {
                @Html.Partial("FeaturedArticlePartial", articleInfo.Article)
            }

        <!--//sreen-gallery-cursual---->
    </div>
</div>


<div class="wrap">
    <div id="main" role="main">
        <ul id="tiles">
            @foreach (var articleInfo in Model.Where(info => !info.IsFeatured))
            {
                @Html.Partial("RegularArticlePartial", articleInfo.Article)
            }
        </ul>
    </div>
</div>

<script src="~/Scripts/jquery.imagesloaded.js"></script>
<script src="~/Scripts/jquery.wookmark.js"></script>
<script type="text/javascript">
    (function ($) {
        var $tiles = $('#tiles'),
            $handler = $('li', $tiles),
            $main = $('#main'),
            $window = $(window),
            $document = $(document),
            options = {
                autoResize: true, // This will auto-update the layout when the browser window is resized.
                container: $main, // Optional, used for some extra CSS styling
                offset: 20, // Optional, the distance between grid items
              //  itemWidth: 460 // Optional, the width of a grid item
            };
        /**
         * Reinitializes the wookmark handler after all images have loaded
         */
        function applyLayout() {
            $tiles.imagesLoaded(function () {
                // Destroy the old handler
                if ($handler.wookmarkInstance) {
                    $handler.wookmarkInstance.clear();
                }

                // Create a new layout handler.
                $handler = $('li', $tiles);
                $handler.wookmark(options);
            });
        }
        /**
         * When scrolled all the way to the bottom, add more tiles
         */
        function onScroll() {
            // Check if we're within 100 pixels of the bottom edge of the broser window.
            var winHeight = window.innerHeight ? window.innerHeight : $window.height(), // iphone fix
                closeToBottom = ($window.scrollTop() + winHeight > $document.height() - 100);

            if (closeToBottom) {
                // Get the first then items from the grid, clone them, and add them to the bottom of the grid
                var $items = $('li', $tiles),
                    $firstTen = $items.slice(0, 10);
                $tiles.append($firstTen.clone());

                applyLayout();
            }
        };

        // Call the layout function for the first time
        applyLayout();

        // Capture scroll event.
        //$window.bind('scroll.wookmark', onScroll);
    })(jQuery);
    </script>
<!----//wookmark-scripts---->

@Html.Partial("_DisqusCommentCount");

NewsDotNet.WebUI/Views/Home/RegularArticlePartial.cshtml
@model NewsDotNet.DomainModel.Entities.Article

<li onclick="location.href='@Url.Action("Show", "Articles", new { addressName = Model.AddressName })';">
    <img src="@Model.TitleImagePath">
    <div class="post-info">
        <div class="post-basic-info">
            <h3>@Model.Title</h3>
            @foreach (var tag in Model.Tags)
            {
                <span><a href="#"><label> </label>@tag.Name</a></span>
            }      
            <p>@Html.Raw(Model.Body.Substring(0, Math.Min(Model.Body.Length, 250)) + "...")</p>
            <p class="comments">
                <span class="glyphicon glyphicon-comment"></span>&nbsp;
                <a data-disqus-identifier="@Model.AddressName"
                   href="@Url.Action("Show", "Articles", new { addressName = Model.AddressName })#disqus_thread">0</a>
            </p>
        </div>
    </div>
</li>

NewsDotNet.WebUI/Views/Shared/_Disqus.cshtml
@model NewsDotNet.DomainModel.Entities.Article

<div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES * * */
    var disqus_shortname = 'newsdotnet';
    var disqus_identifier = '@Model.AddressName';

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function () {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

NewsDotNet.WebUI/Views/Shared/_DisqusCommentCount.cshtml
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES * * */
    var disqus_shortname = 'newsdotnet';

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function () {
        var s = document.createElement('script'); s.async = true;
        s.type = 'text/javascript';
        s.src = '//' + disqus_shortname + '.disqus.com/count.js';
        (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
    }());
</script>

NewsDotNet.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="~/Content/Styles/style.css" rel='stylesheet' type='text/css' />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/x-icon" href="~/Content/Images/Layout/fav-icon.png" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!----webfonts---->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800' rel='stylesheet' type='text/css'>
    <!----//webfonts---->
    <!-- Global CSS for the page and tiles -->
    <link rel="stylesheet" href="~/Content/Styles/main.css">
    <!-- //Global CSS for the page and tiles -->
    <!--Start-click-menu-->
    <script src=@Url.Content("~/Scripts/jquery.min.js")></script>
    <!-- Bootstrap CSS file -->
    <script src="~/Scripts/bootstrap.min.js"></script>
    <link href="~/Content/Styles/bootstrap.min.css" rel="stylesheet" />
    <!-- CSS file for menu -->
    <link href="~/Content/Styles/styleformenu.css" rel='stylesheet' type='text/css' />
    <!-- js file for menu -->
    <script src='~/Scripts/jquery.formenu.js' type='text/javascript'></script>
    <!--//End-click-menu-->
</head>
<body>
    <!---start-wrap---->
    <!---start-header---->
    <div class="header">
        <div class="wrap">
            @*<div class="logo">
                <h3><a href="@Url.Action("Index", "Home")"><p></p>News.NET</a></h3>
            </div>*@
            @* INCLUDE SiteBarMenu *@
            @Html.Partial("_SiteBarMenu")
            <div class="top-searchbar">
                <form>
                    <input type="text" /><input type="submit" value="" />
                </form>
            </div>
            <div class="clear"> </div>
        </div>
    </div>
    <!---//End-header---->
    <!---start-content---->
    <div class="content">
        @RenderBody()
        <br>
    </div>       
        <!----start-footer--->
        <div class="footer">
            <a href="@Url.Action("Index", "Home")"><span class="glyphicon glyphicon-home"></span></a>
        </div>
        <!----//End-footer--->
        <!---//End-wrap---->
</body>
</html>

NewsDotNet.WebUI/Views/Shared/_SiteBarMenu.cshtml
<!--navigation button-->
<div class='main-nav white-bg'>
    <div class='mobile-toggle'>
        <span></span>
        <span></span>
        <span></span>
    </div>
</div>
<!--menu box start-->
<section class='menu-panel fullheight'>
    <div class='row'>
        <article class='col-md-6 fullheight'>
            <div class='valign text-center slogan-holder'>
                <div class='nav-logo-wrap'>
                    <a href='#'>
                        <img alt="NewsDotNet" src="~/Content/Images/Layout/logo.png" />
                    </a>
                    <div class='slogan-wrap'>
                        <h3 class='white font3 slogan-text'>News.Net Co. Working hard</h3>
                    </div>
                </div>
            </div>
        </article>
        <article class='col-md-6 fullheight nav-list-holder white-bg'>
            <div class='valign'>
                <nav class='nav-item-wrap'>
                    <ul class='main-nav-menu main-nav-menu-effect' id='menu-menu-1'>
                        <li><a href="@Url.Action("Index", "Home")"><span>Главная</span></a></li>
                        <li><a href="@Url.Action("Archive", "Articles")"><span>Архив</span></a></li>
                    </ul>
                </nav>
                <div class='copy-credits'>
                </div>
                @* INCLUDE TagsCloud *@
                @Html.Action("TagsCloud", "Tags")
            </div>
        </article>
    </div>
</section>
<!--menu box end-->

NewsDotNet.WebUI/Views/Tags/TagsCloud.cshtml
@model IEnumerable<NewsDotNet.DomainModel.Entities.Tag>
<!-- display tags in sidebar menu -->
<div class="artical-links">
    <ul>
        <li>
            <img src="~/Content/Images/Layout/blog-icon4.png" title="Теги">
            @foreach (var tag in Model)
            {
                <span><a href="#">@tag.Name</a></span>
            }
        </li>
    </ul>
</div>